part of 'app_runtime_factory.dart';

/// Creates the committed AppRuntime view over all phase-owned resources.
extension _AppRuntimeFactoryRuntime on _AppRuntimeFactoryContext {
  AppRuntime _buildRuntime() {
    return AppRuntime(
      appLogService: logger,
      appSettings: appSettings,
      connectionDatabase: runtimeConnectionDatabase,
      connectionRepository: runtimeConnectionRepository,
      credentialRepository: runtimeCredentialRepository,
      hostKeyRepository: runtimeHostKeyRepository,
      networkIdentityService: runtimeNetworkIdentityService,
      networkRuntime: runtimeNetworkRuntime,
      networkFacade: networkFacade,
      realtimeClient: runtimeRealtimeClient,
      realtimeMediaBackend: runtimeRealtimeMediaBackend,
      realtimeMediaSessionFactory: runtimeRealtimeMediaSessionFactory,
      bootstrapCoordinator: bootstrapCoordinator,
      shortcutCommandService: shortcutCommandService,
      terminalSessionMetadataStore: terminalMetadataStore,
      sshSessionManager: terminalSshManager,
      sshService: sshService,
      sshNativeStreamConnector: sshNativeStreamConnector,
      sftpService: sftpService,
      monitoringModule: monitoringModule,
      monitoringService: monitoringService,
      playbookModule: playbookModule,
      playbookSettingsAdapter: playbookSettingsAdapter,
      playbookConnectionCatalogAdapter: playbookConnectionCatalogAdapter,
      ragModule: ragModule,
      ragSettingsAdapter: ragSettingsAdapter,
      mcpModule: mcpModule,
      mcpSettingsAdapter: mcpSettingsAdapter,
      lanShareModule: lanShareModule,
      lanShareSettingsAdapter: lanShareSettingsAdapter,
      webViewService: webViewService,
      webViewSettingsAdapter: webViewSettingsAdapter,
      developerLogAdapter: developerLogAdapter,
      developerSettingsAdapter: developerSettingsAdapter,
      developerDiagnosticsAdapter: developerDiagnosticsAdapter,
      aiModule: aiModule,
      aiStorageAdapter: aiStorageAdapter,
      aiSettingsAdapter: aiSettingsAdapter,
      aiSshAdapter: aiSshAdapter,
      aiSftpAdapter: aiSftpAdapter,
      aiMonitoringAdapter: aiMonitoringAdapter,
      aiClientSystemAdapter: aiClientSystemAdapter,
      aiHealthAdapter: aiHealthAdapter,
      aiWebViewAdapter: aiWebViewAdapter,
      aiServerCatalogAdapter: aiServerCatalogAdapter,
      aiServerDiagnosticsAdapter: aiServerDiagnosticsAdapter,
      aiChatRuntimeFactory: aiChatRuntimeFactory,
      telemetryClient: telemetryClient,
      telemetryConnectivityMonitor: telemetryConnectivityMonitor,
      networkTelemetryBridge: networkTelemetryBridge,
      crashTelemetryBridge: crashTelemetryBridge,
      telemetryLogSink: telemetryLogSink,
      telemetryTraceRegistry: traceRegistry,
      awaitPendingInitialization: pendingInitialization.wait,
      lifecycleObserver: lifecycleObserver,
      disposeLogger: disposeLogger,
    );
  }
}
