//! Golden-vector tests against `protocol/relay_v2_testdata/`.
//!
//! For every fixture in the manifest: read the full wire frame (4-byte BE
//! length prefix + protobuf), decode it, assert every semantic expectation
//! from `manifest.json`, re-encode it, and assert the result is byte-identical
//! to the original file. Also covers the framing negatives (bad length prefix,
//! length mismatch, over max, version != 2, unknown oneof tag tolerated).
//!
//! The fixtures live outside the crate tree (relative path from this crate's
//! root: `../../../../protocol/relay_v2_testdata`); a dedicated test asserts
//! the directory exists to keep that cross-crate path honest.

use std::collections::BTreeSet;
use std::path::Path;

use network_relay_proto::{
    decode_control, decode_data, encode_frame, relay_data_frame, relay_frame, ErrorCode,
    FrameError, RealtimeSignalKind, RelayDataFrame, RelayFrame, ResolveStatus, RuntimeEpoch,
    TransportCapability, MAX_RELAY_FRAME_BYTES, RELAY_V2_VERSION,
};
use serde_json::Value;

/// Repository-root-relative fixture directory, resolved from the crate root.
const FIXTURES_DIR: &str = "../../../../protocol/relay_v2_testdata";
/// Number of `.bin` full-wire fixtures generated by `generate_fixtures.py`.
const EXPECTED_FIXTURE_COUNT: usize = 23;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn read_manifest() -> Value {
    let path = format!("{FIXTURES_DIR}/manifest.json");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {path}: {e}"))
}

fn read_fixture(file: &str) -> Vec<u8> {
    let path = format!("{FIXTURES_DIR}/{file}");
    std::fs::read(&path).unwrap_or_else(|e| panic!("read {path}: {e}"))
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn s<'a>(v: &'a Value, key: &str) -> &'a str {
    v.get(key)
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("expected string field {key:?}"))
}

fn u64_val(v: &Value, key: &str) -> u64 {
    v.get(key)
        .and_then(Value::as_u64)
        .unwrap_or_else(|| panic!("expected u64 field {key:?}"))
}

fn u32_val(v: &Value, key: &str) -> u32 {
    u64_val(v, key) as u32
}

fn i64_val(v: &Value, key: &str) -> i64 {
    v.get(key)
        .and_then(Value::as_i64)
        .unwrap_or_else(|| panic!("expected i64 field {key:?}"))
}

fn i32_val(v: &Value, key: &str) -> i32 {
    u64_val(v, key) as i32
}

fn bool_val(v: &Value, key: &str) -> bool {
    v.get(key)
        .and_then(Value::as_bool)
        .unwrap_or_else(|| panic!("expected bool field {key:?}"))
}

fn assert_epoch(epoch: &RuntimeEpoch, expects: &Value) {
    assert_eq!(format!("0x{:08x}", epoch.high), s(expects, "epoch_high"));
    assert_eq!(format!("0x{:08x}", epoch.low), s(expects, "epoch_low"));
}

// ---------------------------------------------------------------------------
// Semantic assertions
// ---------------------------------------------------------------------------

fn assert_control_fixture(frame: &RelayFrame, expects: &Value, file: &str) {
    assert_eq!(frame.version, RELAY_V2_VERSION, "{file}: frame version");
    match frame
        .kind
        .as_ref()
        .unwrap_or_else(|| panic!("{file}: missing oneof kind"))
    {
        relay_frame::Kind::Ready(m) => {
            assert_eq!(s(expects, "message"), "ready", "{file}");
            assert_eq!(
                m.protocol_version,
                u32_val(expects, "protocol_version"),
                "{file}"
            );
            assert_eq!(m.device_id, s(expects, "device_id"), "{file}");
            assert_eq!(
                m.server_time_ms,
                i64_val(expects, "server_time_ms"),
                "{file}"
            );
            assert_eq!(
                m.heartbeat_interval_s,
                u32_val(expects, "heartbeat_interval_s"),
                "{file}"
            );
            assert_eq!(
                m.presence_ttl_s,
                u32_val(expects, "presence_ttl_s"),
                "{file}"
            );
        }
        relay_frame::Kind::Heartbeat(m) => {
            assert_eq!(s(expects, "message"), "heartbeat", "{file}");
            assert_eq!(m.request_id, u64_val(expects, "request_id"), "{file}");
            assert_eq!(m.sent_at_ms, i64_val(expects, "sent_at_ms"), "{file}");
        }
        relay_frame::Kind::HeartbeatAck(m) => {
            assert_eq!(s(expects, "message"), "heartbeat_ack", "{file}");
            assert_eq!(m.request_id, u64_val(expects, "request_id"), "{file}");
            assert_eq!(
                m.server_time_ms,
                i64_val(expects, "server_time_ms"),
                "{file}"
            );
        }
        relay_frame::Kind::DiscoveryPublish(m) => {
            assert_eq!(s(expects, "message"), "discovery_publish", "{file}");
            assert_eq!(m.request_id, u64_val(expects, "request_id"), "{file}");
            let snapshot = m.snapshot.as_ref().expect("snapshot present");
            assert_epoch(
                snapshot.runtime_epoch.as_ref().expect("runtime epoch"),
                expects,
            );
            assert_eq!(snapshot.revision, u32_val(expects, "revision"), "{file}");
            assert_eq!(
                snapshot.transport_capabilities,
                expects["transport_capabilities"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_i64().unwrap() as i32)
                    .collect::<Vec<i32>>(),
                "{file}: transport_capabilities"
            );
            let names = snapshot
                .transport_capabilities
                .iter()
                .map(|&c| {
                    TransportCapability::try_from(c)
                        .unwrap()
                        .as_str_name()
                        .trim_start_matches("TRANSPORT_CAPABILITY_")
                        .to_string()
                })
                .collect::<Vec<String>>();
            assert_eq!(
                names,
                expects["transport_capability_names"]
                    .as_array()
                    .unwrap()
                    .iter()
                    .map(|v| v.as_str().unwrap().to_string())
                    .collect::<Vec<String>>(),
                "{file}: transport_capability_names"
            );
            assert_eq!(
                snapshot
                    .candidate_bundle
                    .as_ref()
                    .expect("candidate bundle")
                    .candidates
                    .len(),
                u64_val(expects, "candidate_count") as usize,
                "{file}"
            );
            assert_eq!(
                snapshot.published_at_ms,
                i64_val(expects, "published_at_ms"),
                "{file}"
            );
        }
        relay_frame::Kind::DiscoveryAck(m) => {
            assert_eq!(s(expects, "message"), "discovery_ack", "{file}");
            assert_eq!(m.request_id, u64_val(expects, "request_id"), "{file}");
            assert_epoch(m.runtime_epoch.as_ref().expect("runtime epoch"), expects);
            assert_eq!(m.revision, u32_val(expects, "revision"), "{file}");
        }
        relay_frame::Kind::ResolvePeerResponse(m) => {
            assert_eq!(s(expects, "message"), "resolve_peer_response", "{file}");
            assert_eq!(m.request_id, u64_val(expects, "request_id"), "{file}");
            assert_eq!(m.status, i32_val(expects, "status"), "{file}");
            assert_eq!(
                ResolveStatus::try_from(m.status).unwrap().as_str_name(),
                s(expects, "status_name"),
                "{file}"
            );
            if let Some(retry) = expects.get("retry_after_ms") {
                assert_eq!(m.retry_after_ms, retry.as_u64().unwrap() as u32, "{file}");
            }
            match &m.discovery {
                Some(discovery) => {
                    assert!(
                        expects.get("epoch_high").is_some(),
                        "{file}: unexpected discovery"
                    );
                    assert_epoch(
                        discovery.runtime_epoch.as_ref().expect("runtime epoch"),
                        expects,
                    );
                    assert_eq!(discovery.revision, u32_val(expects, "revision"), "{file}");
                }
                None => assert!(
                    expects.get("epoch_high").is_none(),
                    "{file}: expected a discovery snapshot"
                ),
            }
        }
        relay_frame::Kind::ConnectivityOffer(m) => {
            assert_eq!(s(expects, "message"), "connectivity_offer", "{file}");
            assert_eq!(m.request_id, u64_val(expects, "request_id"), "{file}");
            assert_eq!(m.attempt_id, s(expects, "attempt_id"), "{file}");
            assert_eq!(
                m.initiator_device_id,
                s(expects, "initiator_device_id"),
                "{file}"
            );
            assert_epoch(
                m.initiator_runtime_epoch.as_ref().expect("runtime epoch"),
                expects,
            );
            assert_eq!(
                m.initiator_revision,
                u32_val(expects, "initiator_revision"),
                "{file}"
            );
            assert!(
                m.initiator_snapshot.is_some(),
                "{file}: initiator_snapshot present"
            );
        }
        relay_frame::Kind::ConnectivityAnswer(m) => {
            assert_eq!(s(expects, "message"), "connectivity_answer", "{file}");
            assert_eq!(m.request_id, u64_val(expects, "request_id"), "{file}");
            assert_eq!(m.attempt_id, s(expects, "attempt_id"), "{file}");
            assert_eq!(m.accepted, bool_val(expects, "accepted"), "{file}");
            assert_eq!(
                m.responder_device_id,
                s(expects, "responder_device_id"),
                "{file}"
            );
            assert_epoch(
                m.responder_runtime_epoch.as_ref().expect("runtime epoch"),
                expects,
            );
            assert_eq!(
                m.responder_revision,
                u32_val(expects, "responder_revision"),
                "{file}"
            );
            assert!(
                m.responder_snapshot.is_some(),
                "{file}: responder_snapshot present"
            );
        }
        relay_frame::Kind::PresenceHintSnapshot(m) => {
            assert_eq!(s(expects, "message"), "presence_hint_snapshot", "{file}");
            assert_eq!(
                m.published_at_ms,
                i64_val(expects, "published_at_ms"),
                "{file}"
            );
            let peers = &m.peers;
            assert_eq!(
                peers.len(),
                u64_val(expects, "peer_count") as usize,
                "{file}"
            );
            let expected = expects["peers"].as_array().unwrap();
            for (i, peer) in peers.iter().enumerate() {
                let ex = &expected[i];
                assert_eq!(peer.device_id, s(ex, "device_id"), "{file} peers[{i}]");
                assert_eq!(peer.online, bool_val(ex, "online"), "{file} peers[{i}]");
                assert_eq!(peer.revision, u32_val(ex, "revision"), "{file} peers[{i}]");
                assert_epoch(peer.runtime_epoch.as_ref().expect("runtime epoch"), ex);
            }
        }
        relay_frame::Kind::PeerAvailableHint(m) => {
            assert_eq!(s(expects, "message"), "peer_available_hint", "{file}");
            assert_eq!(m.device_id, s(expects, "device_id"), "{file}");
            assert_epoch(m.runtime_epoch.as_ref().expect("runtime epoch"), expects);
            assert_eq!(m.revision, u32_val(expects, "revision"), "{file}");
        }
        relay_frame::Kind::PeerUnavailableHint(m) => {
            assert_eq!(s(expects, "message"), "peer_unavailable_hint", "{file}");
            assert_eq!(m.device_id, s(expects, "device_id"), "{file}");
            assert_eq!(m.reason, s(expects, "reason"), "{file}");
        }
        relay_frame::Kind::RelayReserveRequest(m) => {
            assert_eq!(s(expects, "message"), "relay_reserve_request", "{file}");
            assert_eq!(m.request_id, u64_val(expects, "request_id"), "{file}");
            assert_eq!(m.attempt_id, s(expects, "attempt_id"), "{file}");
            assert_eq!(m.target_device_id, s(expects, "target_device_id"), "{file}");
            assert_eq!(
                m.desired_lifetime_s,
                u32_val(expects, "desired_lifetime_s"),
                "{file}"
            );
        }
        relay_frame::Kind::RelayReserveResponse(m) => {
            assert_eq!(s(expects, "message"), "relay_reserve_response", "{file}");
            assert_eq!(m.request_id, u64_val(expects, "request_id"), "{file}");
            assert_eq!(m.attempt_id, s(expects, "attempt_id"), "{file}");
            assert_eq!(m.reservation_id, s(expects, "reservation_id"), "{file}");
            assert_eq!(
                m.relay_data_endpoint,
                s(expects, "relay_data_endpoint"),
                "{file}"
            );
            assert_eq!(m.expires_at_ms, i64_val(expects, "expires_at_ms"), "{file}");
            assert_eq!(hex(&m.local_token), s(expects, "local_token_hex"), "{file}");
        }
        relay_frame::Kind::IncomingRelayReservation(m) => {
            assert_eq!(
                s(expects, "message"),
                "incoming_relay_reservation",
                "{file}"
            );
            assert_eq!(m.attempt_id, s(expects, "attempt_id"), "{file}");
            assert_eq!(m.reservation_id, s(expects, "reservation_id"), "{file}");
            assert_eq!(
                m.initiator_device_id,
                s(expects, "initiator_device_id"),
                "{file}"
            );
            assert_eq!(
                m.relay_data_endpoint,
                s(expects, "relay_data_endpoint"),
                "{file}"
            );
            assert_eq!(m.expires_at_ms, i64_val(expects, "expires_at_ms"), "{file}");
            assert_eq!(hex(&m.local_token), s(expects, "local_token_hex"), "{file}");
        }
        relay_frame::Kind::RealtimeSignal(m) => {
            assert_eq!(s(expects, "message"), "realtime_signal", "{file}");
            assert_eq!(m.request_id, u64_val(expects, "request_id"), "{file}");
            assert_eq!(m.realtime_id, s(expects, "realtime_id"), "{file}");
            assert_eq!(m.target_device_id, s(expects, "target_device_id"), "{file}");
            assert_eq!(m.kind, i32_val(expects, "kind"), "{file}");
            assert_eq!(
                RealtimeSignalKind::try_from(m.kind).unwrap().as_str_name(),
                s(expects, "kind_name"),
                "{file}"
            );
            assert_eq!(m.revision, u64_val(expects, "revision"), "{file}");
            assert_eq!(hex(&m.payload), s(expects, "payload_hex"), "{file}");
        }
        relay_frame::Kind::ProtocolError(m) => {
            assert_eq!(s(expects, "message"), "protocol_error", "{file}");
            assert_eq!(m.request_id, u64_val(expects, "request_id"), "{file}");
            assert_eq!(m.attempt_id, s(expects, "attempt_id"), "{file}");
            assert_eq!(m.code, i32_val(expects, "code"), "{file}");
            assert_eq!(
                ErrorCode::try_from(m.code).unwrap().as_str_name(),
                s(expects, "code_name"),
                "{file}"
            );
            assert_eq!(m.message, s(expects, "error_message"), "{file}");
        }
        relay_frame::Kind::ResolvePeerRequest(_) => {
            panic!("{file}: no golden fixture uses ResolvePeerRequest")
        }
    }
}

fn assert_data_fixture(frame: &RelayDataFrame, expects: &Value, file: &str) {
    assert_eq!(frame.version, RELAY_V2_VERSION, "{file}: frame version");
    match frame
        .kind
        .as_ref()
        .unwrap_or_else(|| panic!("{file}: missing oneof kind"))
    {
        relay_data_frame::Kind::Connect(m) => {
            assert_eq!(s(expects, "message"), "relay_data_connect", "{file}");
            assert_eq!(m.reservation_id, s(expects, "reservation_id"), "{file}");
            assert_eq!(hex(&m.local_token), s(expects, "local_token_hex"), "{file}");
        }
        relay_data_frame::Kind::Payload(m) => {
            assert_eq!(s(expects, "message"), "relay_data_payload", "{file}");
            assert_eq!(m.sequence, u64_val(expects, "sequence"), "{file}");
            assert_eq!(
                hex(&m.encrypted_payload),
                s(expects, "encrypted_payload_hex"),
                "{file}"
            );
        }
        relay_data_frame::Kind::Ack(m) => {
            assert_eq!(s(expects, "message"), "relay_data_ack", "{file}");
            assert_eq!(m.sequence, u64_val(expects, "sequence"), "{file}");
        }
        relay_data_frame::Kind::Close(m) => {
            assert_eq!(s(expects, "message"), "relay_data_close", "{file}");
            assert_eq!(m.reason, u32_val(expects, "reason"), "{file}");
        }
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn fixtures_directory_exists() {
    assert!(
        Path::new(FIXTURES_DIR).is_dir(),
        "fixtures dir missing at {FIXTURES_DIR} (run tests from the crate root)"
    );
}

#[test]
fn manifest_covers_exactly_the_bin_files_on_disk() {
    use walkdir::WalkDir;
    let dir = Path::new(FIXTURES_DIR);
    assert!(dir.is_dir(), "fixtures dir missing at {FIXTURES_DIR}");
    let manifest = read_manifest();
    let manifest_files: BTreeSet<String> = manifest["fixtures"]
        .as_array()
        .unwrap()
        .iter()
        .map(|fx| fx["file"].as_str().unwrap().to_string())
        .collect();
    assert_eq!(manifest_files.len(), EXPECTED_FIXTURE_COUNT);
    let on_disk: BTreeSet<String> = WalkDir::new(dir)
        .into_iter()
        .filter_map(Result::ok)
        .filter(|e| e.file_type().is_file() && e.path().extension().is_some_and(|x| x == "bin"))
        .filter_map(|e| {
            e.path()
                .file_name()
                .map(|n| n.to_string_lossy().into_owned())
        })
        .collect();
    assert_eq!(on_disk.len(), EXPECTED_FIXTURE_COUNT);
    assert_eq!(
        manifest_files, on_disk,
        "manifest fixture set must equal the .bin files on disk"
    );
}

#[test]
fn constants_match_manifest() {
    let manifest = read_manifest();
    let constants = &manifest["constants"];
    let assert_u32 = |key: &str, value: u32| {
        assert_eq!(
            constants.get(key).unwrap().as_u64().unwrap() as u32,
            value,
            "manifest constant {key}"
        );
    };
    let assert_usize = |key: &str, value: usize| {
        assert_eq!(
            constants.get(key).unwrap().as_u64().unwrap() as usize,
            value,
            "manifest constant {key}"
        );
    };
    assert_usize(
        "FRAME_LENGTH_PREFIX_BYTES",
        network_relay_proto::FRAME_LENGTH_PREFIX_BYTES,
    );
    assert_usize(
        "MAX_RELAY_FRAME_BYTES",
        network_relay_proto::MAX_RELAY_FRAME_BYTES,
    );
    assert_usize(
        "MAX_RELAY_DATA_FRAME_BYTES",
        network_relay_proto::MAX_RELAY_DATA_FRAME_BYTES,
    );
    assert_usize(
        "MAX_DEVICE_ID_BYTES",
        network_relay_proto::MAX_DEVICE_ID_BYTES,
    );
    assert_usize(
        "MAX_ATTEMPT_ID_BYTES",
        network_relay_proto::MAX_ATTEMPT_ID_BYTES,
    );
    assert_usize(
        "MAX_REALTIME_SIGNAL_PAYLOAD_BYTES",
        network_relay_proto::MAX_REALTIME_SIGNAL_PAYLOAD_BYTES,
    );
    assert_usize(
        "MAX_DISCOVERY_CANDIDATES",
        network_relay_proto::MAX_DISCOVERY_CANDIDATES,
    );
    assert_usize(
        "MAX_DISCOVERY_CANDIDATE_BYTES",
        network_relay_proto::MAX_DISCOVERY_CANDIDATE_BYTES,
    );
    assert_usize(
        "MAX_DISCOVERY_CAPABILITIES",
        network_relay_proto::MAX_DISCOVERY_CAPABILITIES,
    );
    assert_usize(
        "RESERVATION_ID_BYTES",
        network_relay_proto::RESERVATION_ID_BYTES,
    );
    assert_usize(
        "RESERVATION_TOKEN_BYTES",
        network_relay_proto::RESERVATION_TOKEN_BYTES,
    );
    assert_u32(
        "HEARTBEAT_INTERVAL_S",
        network_relay_proto::HEARTBEAT_INTERVAL_S,
    );
    assert_u32("PRESENCE_TTL_S", network_relay_proto::PRESENCE_TTL_S);
    assert_u32(
        "SERVER_HEARTBEAT_MISSES_BEFORE_CLOSE",
        network_relay_proto::SERVER_HEARTBEAT_MISSES_BEFORE_CLOSE,
    );
    assert_u32(
        "RESERVATION_LIFETIME_S_DEFAULT",
        network_relay_proto::RESERVATION_LIFETIME_S_DEFAULT,
    );
    assert_u32(
        "RESERVATION_EXPIRY_GRACE_S",
        network_relay_proto::RESERVATION_EXPIRY_GRACE_S,
    );
    assert_u32(
        "RESOLVE_RETRY_HINT_NOT_READY_MS",
        network_relay_proto::RESOLVE_RETRY_HINT_NOT_READY_MS,
    );
    assert_u32(
        "RESOLVE_RETRY_HINT_UNKNOWN_MS",
        network_relay_proto::RESOLVE_RETRY_HINT_UNKNOWN_MS,
    );
    assert_u32(
        "DIRECT_CONNECT_WINDOW_MS",
        network_relay_proto::DIRECT_CONNECT_WINDOW_MS,
    );
}

#[test]
fn every_fixture_decodes_matches_manifest_and_round_trips_byte_identical() {
    let manifest = read_manifest();
    let fixtures = manifest["fixtures"].as_array().unwrap();
    assert_eq!(fixtures.len(), EXPECTED_FIXTURE_COUNT);

    for fx in fixtures {
        let file = fx["file"].as_str().unwrap();
        let transport = fx["transport"].as_str().unwrap();
        let expects = &fx["expects"];
        let data = read_fixture(file);

        match transport {
            "control" => {
                let decoded =
                    decode_control(&data).unwrap_or_else(|e| panic!("decode {file}: {e}"));
                assert_control_fixture(&decoded, expects, file);
                let reencoded = encode_frame(&decoded);
                assert_eq!(reencoded, data, "re-encode {file} must be byte-identical");
            }
            "data" => {
                let decoded = decode_data(&data).unwrap_or_else(|e| panic!("decode {file}: {e}"));
                assert_data_fixture(&decoded, expects, file);
                let reencoded = encode_frame(&decoded);
                assert_eq!(reencoded, data, "re-encode {file} must be byte-identical");
            }
            other => panic!("{file}: unknown transport {other:?}"),
        }
    }
}

#[test]
fn framing_negatives() {
    // Too short for the 4-byte length prefix.
    assert!(matches!(
        decode_control(&[0x00, 0x01, 0x02]),
        Err(FrameError::TooShort)
    ));

    // Length prefix mismatch: prefix says 256, actual payload is 2 bytes.
    let bad_prefix = [0x00u8, 0x00, 0x01, 0x00, 0x08, 0x02];
    assert!(matches!(
        decode_control(&bad_prefix),
        Err(FrameError::LengthMismatch {
            prefix: 256,
            actual: 2
        })
    ));

    // Zero prefix with a non-empty payload.
    let mut zero_prefix = vec![0u8; network_relay_proto::FRAME_LENGTH_PREFIX_BYTES];
    zero_prefix.extend_from_slice(&[0x08, 0x02]);
    assert!(matches!(
        decode_control(&zero_prefix),
        Err(FrameError::LengthMismatch {
            prefix: 0,
            actual: 2
        })
    ));

    // Frame exceeds MAX_RELAY_FRAME_BYTES (matching prefix, too-long payload).
    let over_max_body = MAX_RELAY_FRAME_BYTES - network_relay_proto::FRAME_LENGTH_PREFIX_BYTES + 16;
    let mut over =
        Vec::with_capacity(network_relay_proto::FRAME_LENGTH_PREFIX_BYTES + over_max_body);
    over.extend_from_slice(&(over_max_body as u32).to_be_bytes());
    over.resize(
        network_relay_proto::FRAME_LENGTH_PREFIX_BYTES + over_max_body,
        0u8,
    );
    assert!(matches!(
        decode_control(&over),
        Err(FrameError::TooLarge { max: MAX_RELAY_FRAME_BYTES, actual }) if actual == over.len()
    ));

    // Version != 2: well-formed frame with version=1 and no kind.
    let wrong_version = RelayFrame {
        version: 1,
        kind: None,
    };
    let encoded = encode_frame(&wrong_version);
    assert!(matches!(
        decode_control(&encoded),
        Err(FrameError::InvalidVersion {
            version: 1,
            expected: RELAY_V2_VERSION
        })
    ));

    // Unknown oneof tag is tolerated (proto3 skips unknown fields): version=2
    // plus an unknown field 27 (wire type 2). tag == (27<<3)|2 == 218.
    let unknown = [0x08u8, 0x02, 0xda, 0x01, 0x02, 0x00, 0x00];
    let mut with_prefix =
        Vec::with_capacity(network_relay_proto::FRAME_LENGTH_PREFIX_BYTES + unknown.len());
    with_prefix.extend_from_slice(&(unknown.len() as u32).to_be_bytes());
    with_prefix.extend_from_slice(&unknown);
    let decoded = decode_control(&with_prefix).expect("unknown oneof tag is tolerated");
    assert_eq!(decoded.version, RELAY_V2_VERSION);
    assert!(
        decoded.kind.is_none(),
        "unknown oneof tag leaves kind unset"
    );

    // Same tolerances hold on the data route; a versionless data frame decodes.
    let data = RelayDataFrame {
        version: RELAY_V2_VERSION,
        kind: None,
    };
    let data_encoded = encode_frame(&data);
    let decoded_data = decode_data(&data_encoded).expect("data frame decode");
    assert_eq!(decoded_data.version, RELAY_V2_VERSION);
}
