// Relay control protocol v2 — FROZEN wire contract.
//
// This file is the single source of truth for the transport-network v2 relay
// control plane and relay data plane. Field tags and semantics below are
// FROZEN: do not renumber, do not repurpose a reserved tag, do not silently
// change semantics. Downstream codecs (Rust prost in native/network_core,
// Go protobuf in relay/internal/relay/v2) and the golden fixtures in
// protocol/relay_v2_testdata/ are locked to this file.
//
// Centralized constants (mirrored in protocol/relay_v2_testdata/manifest.json
// and in each codec; no magic numbers anywhere else):
//   RELAY_V2_VERSION                       = 2
//   FRAME_LENGTH_PREFIX_BYTES              = 4           // [u32 big-endian length][protobuf]
//   MAX_RELAY_FRAME_BYTES                  = 4 + 512 * 1024
//   MAX_RELAY_DATA_FRAME_BYTES             = 4 + 512 * 1024
//   MAX_DEVICE_ID_BYTES                    = 128
//   MAX_ATTEMPT_ID_BYTES                   = 128
//   MAX_REALTIME_ID_BYTES                  = 128
//   MAX_REALTIME_SIGNAL_PAYLOAD_BYTES      = 256 * 1024
//   MAX_DISCOVERY_CANDIDATES               = 64
//   MAX_DISCOVERY_CANDIDATE_BYTES          = 4096
//   MAX_DISCOVERY_CAPABILITIES             = 64
//   RESERVATION_ID_BYTES                   = 16          // 32 hex chars
//   RESERVATION_TOKEN_BYTES                = 32
//   HEARTBEAT_INTERVAL_S                   = 20
//   PRESENCE_TTL_S                         = 60
//   SERVER_HEARTBEAT_MISSES_BEFORE_CLOSE   = 2           // 60s TTL / 20s
//   RESERVATION_LIFETIME_S_DEFAULT         = 60          // server clamps [15, 120]
//   RESERVATION_EXPIRY_GRACE_S             = 5
//   RESOLVE_RETRY_HINT_NOT_READY_MS        = 2000
//   RESOLVE_RETRY_HINT_UNKNOWN_MS          = 5000
//   DIRECT_CONNECT_WINDOW_MS               = 4000        // fixed; not carried on the wire
//
// Frame envelope (both routes):
//   WS Binary payload == [4-byte big-endian length][protobuf RelayFrame]
//   or                == [4-byte big-endian length][protobuf RelayDataFrame]
//   Exactly ONE message per WS frame; length MUST equal frame.len() - 4.
//   A RelayDataFrame on /v2/control (or a RelayFrame on /v2/relay) is a
//   protocol violation and closes the connection.
//
// Route semantics:
//   GET /v2/control               — long-lived control plane; ONLY RelayFrame.
//   GET /v2/relay/{reservation_id} — reservation-scoped opaque data plane; ONLY RelayDataFrame.
//
// Correlation model:
//   Every request carries request_id (uint64). Every async attempt carries
//   attempt_id (string <= 128 bytes). Responses echo request_id; async
//   attempts correlate by attempt_id. No global Notify.
//
// The v1->v2 mapping table and the message inventory are maintained in
// protocol/RELAY_V2_CONTRACT.md (lockstep authority).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: relay/v2/relay_v2.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Transport capability a peer advertises in its DiscoverySnapshot.
// Value numbers are frozen; the enum-name prefix follows the network.v1
// convention so value identifiers stay unique within the package.
type TransportCapability int32

const (
	TransportCapability_TRANSPORT_CAPABILITY_UNSPECIFIED  TransportCapability = 0
	TransportCapability_TRANSPORT_CAPABILITY_QUIC         TransportCapability = 1
	TransportCapability_TRANSPORT_CAPABILITY_TCP          TransportCapability = 2
	TransportCapability_TRANSPORT_CAPABILITY_UDP_DATAGRAM TransportCapability = 3
	TransportCapability_TRANSPORT_CAPABILITY_WEBSOCKET    TransportCapability = 4
	TransportCapability_TRANSPORT_CAPABILITY_WEBRTC       TransportCapability = 5
	TransportCapability_TRANSPORT_CAPABILITY_RELAY_DATA   TransportCapability = 6
)

// Enum value maps for TransportCapability.
var (
	TransportCapability_name = map[int32]string{
		0: "TRANSPORT_CAPABILITY_UNSPECIFIED",
		1: "TRANSPORT_CAPABILITY_QUIC",
		2: "TRANSPORT_CAPABILITY_TCP",
		3: "TRANSPORT_CAPABILITY_UDP_DATAGRAM",
		4: "TRANSPORT_CAPABILITY_WEBSOCKET",
		5: "TRANSPORT_CAPABILITY_WEBRTC",
		6: "TRANSPORT_CAPABILITY_RELAY_DATA",
	}
	TransportCapability_value = map[string]int32{
		"TRANSPORT_CAPABILITY_UNSPECIFIED":  0,
		"TRANSPORT_CAPABILITY_QUIC":         1,
		"TRANSPORT_CAPABILITY_TCP":          2,
		"TRANSPORT_CAPABILITY_UDP_DATAGRAM": 3,
		"TRANSPORT_CAPABILITY_WEBSOCKET":    4,
		"TRANSPORT_CAPABILITY_WEBRTC":       5,
		"TRANSPORT_CAPABILITY_RELAY_DATA":   6,
	}
)

func (x TransportCapability) Enum() *TransportCapability {
	p := new(TransportCapability)
	*p = x
	return p
}

func (x TransportCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_v2_relay_v2_proto_enumTypes[0].Descriptor()
}

func (TransportCapability) Type() protoreflect.EnumType {
	return &file_relay_v2_relay_v2_proto_enumTypes[0]
}

func (x TransportCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportCapability.Descriptor instead.
func (TransportCapability) EnumDescriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{0}
}

// Result of a peer lookup. There is no fail-open "online=true default".
type ResolveStatus int32

const (
	ResolveStatus_RESOLVE_STATUS_UNSPECIFIED ResolveStatus = 0
	ResolveStatus_RESOLVE_STATUS_READY       ResolveStatus = 1
	ResolveStatus_RESOLVE_STATUS_OFFLINE     ResolveStatus = 2
	ResolveStatus_RESOLVE_STATUS_NOT_READY   ResolveStatus = 3
	ResolveStatus_RESOLVE_STATUS_UNKNOWN     ResolveStatus = 4
)

// Enum value maps for ResolveStatus.
var (
	ResolveStatus_name = map[int32]string{
		0: "RESOLVE_STATUS_UNSPECIFIED",
		1: "RESOLVE_STATUS_READY",
		2: "RESOLVE_STATUS_OFFLINE",
		3: "RESOLVE_STATUS_NOT_READY",
		4: "RESOLVE_STATUS_UNKNOWN",
	}
	ResolveStatus_value = map[string]int32{
		"RESOLVE_STATUS_UNSPECIFIED": 0,
		"RESOLVE_STATUS_READY":       1,
		"RESOLVE_STATUS_OFFLINE":     2,
		"RESOLVE_STATUS_NOT_READY":   3,
		"RESOLVE_STATUS_UNKNOWN":     4,
	}
)

func (x ResolveStatus) Enum() *ResolveStatus {
	p := new(ResolveStatus)
	*p = x
	return p
}

func (x ResolveStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolveStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_v2_relay_v2_proto_enumTypes[1].Descriptor()
}

func (ResolveStatus) Type() protoreflect.EnumType {
	return &file_relay_v2_relay_v2_proto_enumTypes[1]
}

func (x ResolveStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolveStatus.Descriptor instead.
func (ResolveStatus) EnumDescriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{1}
}

// Real-time media signal kind. Values 1..5 intentionally mirror
// network.v1.RealtimeSignalKind (a unit test asserts they stay in sync).
type RealtimeSignalKind int32

const (
	RealtimeSignalKind_REALTIME_SIGNAL_KIND_UNSPECIFIED   RealtimeSignalKind = 0
	RealtimeSignalKind_REALTIME_SIGNAL_KIND_OFFER         RealtimeSignalKind = 1
	RealtimeSignalKind_REALTIME_SIGNAL_KIND_ANSWER        RealtimeSignalKind = 2
	RealtimeSignalKind_REALTIME_SIGNAL_KIND_ICE_CANDIDATE RealtimeSignalKind = 3
	RealtimeSignalKind_REALTIME_SIGNAL_KIND_ICE_RESTART   RealtimeSignalKind = 4
	RealtimeSignalKind_REALTIME_SIGNAL_KIND_CLOSE         RealtimeSignalKind = 5
)

// Enum value maps for RealtimeSignalKind.
var (
	RealtimeSignalKind_name = map[int32]string{
		0: "REALTIME_SIGNAL_KIND_UNSPECIFIED",
		1: "REALTIME_SIGNAL_KIND_OFFER",
		2: "REALTIME_SIGNAL_KIND_ANSWER",
		3: "REALTIME_SIGNAL_KIND_ICE_CANDIDATE",
		4: "REALTIME_SIGNAL_KIND_ICE_RESTART",
		5: "REALTIME_SIGNAL_KIND_CLOSE",
	}
	RealtimeSignalKind_value = map[string]int32{
		"REALTIME_SIGNAL_KIND_UNSPECIFIED":   0,
		"REALTIME_SIGNAL_KIND_OFFER":         1,
		"REALTIME_SIGNAL_KIND_ANSWER":        2,
		"REALTIME_SIGNAL_KIND_ICE_CANDIDATE": 3,
		"REALTIME_SIGNAL_KIND_ICE_RESTART":   4,
		"REALTIME_SIGNAL_KIND_CLOSE":         5,
	}
)

func (x RealtimeSignalKind) Enum() *RealtimeSignalKind {
	p := new(RealtimeSignalKind)
	*p = x
	return p
}

func (x RealtimeSignalKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RealtimeSignalKind) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_v2_relay_v2_proto_enumTypes[2].Descriptor()
}

func (RealtimeSignalKind) Type() protoreflect.EnumType {
	return &file_relay_v2_relay_v2_proto_enumTypes[2]
}

func (x RealtimeSignalKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RealtimeSignalKind.Descriptor instead.
func (RealtimeSignalKind) EnumDescriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{2}
}

// Unified protocol error model (§33). No generic RelayError/IoError
// fallthrough on the wire.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED           ErrorCode = 0
	ErrorCode_ERROR_CODE_CONTROL_UNAVAILABLE   ErrorCode = 1
	ErrorCode_ERROR_CODE_AUTHENTICATION_FAILED ErrorCode = 2
	ErrorCode_ERROR_CODE_PEER_OFFLINE          ErrorCode = 3
	ErrorCode_ERROR_CODE_PEER_NOT_READY        ErrorCode = 4
	ErrorCode_ERROR_CODE_RESOLVE_TIMEOUT       ErrorCode = 5
	ErrorCode_ERROR_CODE_PROTOCOL              ErrorCode = 6
	ErrorCode_ERROR_CODE_EPOCH_CONFLICT        ErrorCode = 7
	ErrorCode_ERROR_CODE_REVISION_STALE        ErrorCode = 8
	ErrorCode_ERROR_CODE_RESERVATION_FAILED    ErrorCode = 9
	ErrorCode_ERROR_CODE_RESERVATION_EXPIRED   ErrorCode = 10
	ErrorCode_ERROR_CODE_RELAY_UNAVAILABLE     ErrorCode = 11
	ErrorCode_ERROR_CODE_RATE_LIMITED          ErrorCode = 12
	ErrorCode_ERROR_CODE_MALFORMED_FRAME       ErrorCode = 13
	ErrorCode_ERROR_CODE_FRAME_TOO_LARGE       ErrorCode = 14
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "ERROR_CODE_UNSPECIFIED",
		1:  "ERROR_CODE_CONTROL_UNAVAILABLE",
		2:  "ERROR_CODE_AUTHENTICATION_FAILED",
		3:  "ERROR_CODE_PEER_OFFLINE",
		4:  "ERROR_CODE_PEER_NOT_READY",
		5:  "ERROR_CODE_RESOLVE_TIMEOUT",
		6:  "ERROR_CODE_PROTOCOL",
		7:  "ERROR_CODE_EPOCH_CONFLICT",
		8:  "ERROR_CODE_REVISION_STALE",
		9:  "ERROR_CODE_RESERVATION_FAILED",
		10: "ERROR_CODE_RESERVATION_EXPIRED",
		11: "ERROR_CODE_RELAY_UNAVAILABLE",
		12: "ERROR_CODE_RATE_LIMITED",
		13: "ERROR_CODE_MALFORMED_FRAME",
		14: "ERROR_CODE_FRAME_TOO_LARGE",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":           0,
		"ERROR_CODE_CONTROL_UNAVAILABLE":   1,
		"ERROR_CODE_AUTHENTICATION_FAILED": 2,
		"ERROR_CODE_PEER_OFFLINE":          3,
		"ERROR_CODE_PEER_NOT_READY":        4,
		"ERROR_CODE_RESOLVE_TIMEOUT":       5,
		"ERROR_CODE_PROTOCOL":              6,
		"ERROR_CODE_EPOCH_CONFLICT":        7,
		"ERROR_CODE_REVISION_STALE":        8,
		"ERROR_CODE_RESERVATION_FAILED":    9,
		"ERROR_CODE_RESERVATION_EXPIRED":   10,
		"ERROR_CODE_RELAY_UNAVAILABLE":     11,
		"ERROR_CODE_RATE_LIMITED":          12,
		"ERROR_CODE_MALFORMED_FRAME":       13,
		"ERROR_CODE_FRAME_TOO_LARGE":       14,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_relay_v2_relay_v2_proto_enumTypes[3].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_relay_v2_relay_v2_proto_enumTypes[3]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{3}
}

// 128-bit random runtime identity, big-endian (high, low). Two fixed64 keep
// the value byte-stable and unambiguous across Go (no u128), Rust (u128 from
// (high<<64)|low) and the golden fixtures.
type RuntimeEpoch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	High          uint64                 `protobuf:"fixed64,1,opt,name=high,proto3" json:"high,omitempty"`
	Low           uint64                 `protobuf:"fixed64,2,opt,name=low,proto3" json:"low,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeEpoch) Reset() {
	*x = RuntimeEpoch{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeEpoch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeEpoch) ProtoMessage() {}

func (x *RuntimeEpoch) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeEpoch.ProtoReflect.Descriptor instead.
func (*RuntimeEpoch) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeEpoch) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *RuntimeEpoch) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

// Opaque native-encoded candidate blobs; the relay NEVER parses them.
type CandidateBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    [][]byte               `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidateBundle) Reset() {
	*x = CandidateBundle{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidateBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidateBundle) ProtoMessage() {}

func (x *CandidateBundle) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidateBundle.ProtoReflect.Descriptor instead.
func (*CandidateBundle) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{1}
}

func (x *CandidateBundle) GetCandidates() [][]byte {
	if x != nil {
		return x.Candidates
	}
	return nil
}

// A peer's published discovery. revision is the ONLY ordering signal and is
// meaningful only within a single runtime_epoch (cross-epoch revisions are
// incomparable).
type DiscoverySnapshot struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RuntimeEpoch          *RuntimeEpoch          `protobuf:"bytes,1,opt,name=runtime_epoch,json=runtimeEpoch,proto3" json:"runtime_epoch,omitempty"`
	Revision              uint32                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"` // monotonic within epoch, >= 1
	TransportCapabilities []TransportCapability  `protobuf:"varint,3,rep,packed,name=transport_capabilities,json=transportCapabilities,proto3,enum=relay.v2.TransportCapability" json:"transport_capabilities,omitempty"`
	CandidateBundle       *CandidateBundle       `protobuf:"bytes,4,opt,name=candidate_bundle,json=candidateBundle,proto3" json:"candidate_bundle,omitempty"`
	PublishedAtMs         int64                  `protobuf:"varint,5,opt,name=published_at_ms,json=publishedAtMs,proto3" json:"published_at_ms,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DiscoverySnapshot) Reset() {
	*x = DiscoverySnapshot{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverySnapshot) ProtoMessage() {}

func (x *DiscoverySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverySnapshot.ProtoReflect.Descriptor instead.
func (*DiscoverySnapshot) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoverySnapshot) GetRuntimeEpoch() *RuntimeEpoch {
	if x != nil {
		return x.RuntimeEpoch
	}
	return nil
}

func (x *DiscoverySnapshot) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *DiscoverySnapshot) GetTransportCapabilities() []TransportCapability {
	if x != nil {
		return x.TransportCapabilities
	}
	return nil
}

func (x *DiscoverySnapshot) GetCandidateBundle() *CandidateBundle {
	if x != nil {
		return x.CandidateBundle
	}
	return nil
}

func (x *DiscoverySnapshot) GetPublishedAtMs() int64 {
	if x != nil {
		return x.PublishedAtMs
	}
	return 0
}

type Ready struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion    uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"` // always 2
	DeviceId           string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ServerTimeMs       int64                  `protobuf:"varint,3,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	HeartbeatIntervalS uint32                 `protobuf:"varint,4,opt,name=heartbeat_interval_s,json=heartbeatIntervalS,proto3" json:"heartbeat_interval_s,omitempty"` // fixed 20, server-confirmed
	PresenceTtlS       uint32                 `protobuf:"varint,5,opt,name=presence_ttl_s,json=presenceTtlS,proto3" json:"presence_ttl_s,omitempty"`                   // fixed 60, server-confirmed
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Ready) Reset() {
	*x = Ready{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{3}
}

func (x *Ready) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Ready) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Ready) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *Ready) GetHeartbeatIntervalS() uint32 {
	if x != nil {
		return x.HeartbeatIntervalS
	}
	return 0
}

func (x *Ready) GetPresenceTtlS() uint32 {
	if x != nil {
		return x.PresenceTtlS
	}
	return 0
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SentAtMs      int64                  `protobuf:"varint,2,opt,name=sent_at_ms,json=sentAtMs,proto3" json:"sent_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{4}
}

func (x *Heartbeat) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Heartbeat) GetSentAtMs() int64 {
	if x != nil {
		return x.SentAtMs
	}
	return 0
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ServerTimeMs  int64                  `protobuf:"varint,2,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatAck) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *HeartbeatAck) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

type DiscoveryPublish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Snapshot      *DiscoverySnapshot     `protobuf:"bytes,2,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryPublish) Reset() {
	*x = DiscoveryPublish{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryPublish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryPublish) ProtoMessage() {}

func (x *DiscoveryPublish) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryPublish.ProtoReflect.Descriptor instead.
func (*DiscoveryPublish) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{6}
}

func (x *DiscoveryPublish) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DiscoveryPublish) GetSnapshot() *DiscoverySnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type DiscoveryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RuntimeEpoch  *RuntimeEpoch          `protobuf:"bytes,2,opt,name=runtime_epoch,json=runtimeEpoch,proto3" json:"runtime_epoch,omitempty"`
	Revision      uint32                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryAck) Reset() {
	*x = DiscoveryAck{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryAck) ProtoMessage() {}

func (x *DiscoveryAck) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryAck.ProtoReflect.Descriptor instead.
func (*DiscoveryAck) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{7}
}

func (x *DiscoveryAck) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *DiscoveryAck) GetRuntimeEpoch() *RuntimeEpoch {
	if x != nil {
		return x.RuntimeEpoch
	}
	return nil
}

func (x *DiscoveryAck) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ResolvePeerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TargetDeviceId string                 `protobuf:"bytes,2,opt,name=target_device_id,json=targetDeviceId,proto3" json:"target_device_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolvePeerRequest) Reset() {
	*x = ResolvePeerRequest{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePeerRequest) ProtoMessage() {}

func (x *ResolvePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePeerRequest.ProtoReflect.Descriptor instead.
func (*ResolvePeerRequest) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{8}
}

func (x *ResolvePeerRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ResolvePeerRequest) GetTargetDeviceId() string {
	if x != nil {
		return x.TargetDeviceId
	}
	return ""
}

type ResolvePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        ResolveStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=relay.v2.ResolveStatus" json:"status,omitempty"`       // READY/OFFLINE/NOT_READY/UNKNOWN
	Discovery     *DiscoverySnapshot     `protobuf:"bytes,3,opt,name=discovery,proto3" json:"discovery,omitempty"`                              // present iff READY
	RetryAfterMs  uint32                 `protobuf:"varint,4,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"` // NOT_READY: 2000; UNKNOWN: 5000 (hint)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePeerResponse) Reset() {
	*x = ResolvePeerResponse{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePeerResponse) ProtoMessage() {}

func (x *ResolvePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePeerResponse.ProtoReflect.Descriptor instead.
func (*ResolvePeerResponse) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{9}
}

func (x *ResolvePeerResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ResolvePeerResponse) GetStatus() ResolveStatus {
	if x != nil {
		return x.Status
	}
	return ResolveStatus_RESOLVE_STATUS_UNSPECIFIED
}

func (x *ResolvePeerResponse) GetDiscovery() *DiscoverySnapshot {
	if x != nil {
		return x.Discovery
	}
	return nil
}

func (x *ResolvePeerResponse) GetRetryAfterMs() uint32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

type ConnectivityOffer struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RequestId             uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // initiator's control-connection request id
	AttemptId             string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`  // async attempt correlation key
	InitiatorDeviceId     string                 `protobuf:"bytes,3,opt,name=initiator_device_id,json=initiatorDeviceId,proto3" json:"initiator_device_id,omitempty"`
	InitiatorRuntimeEpoch *RuntimeEpoch          `protobuf:"bytes,4,opt,name=initiator_runtime_epoch,json=initiatorRuntimeEpoch,proto3" json:"initiator_runtime_epoch,omitempty"`
	InitiatorRevision     uint32                 `protobuf:"varint,5,opt,name=initiator_revision,json=initiatorRevision,proto3" json:"initiator_revision,omitempty"`
	InitiatorSnapshot     *DiscoverySnapshot     `protobuf:"bytes,6,opt,name=initiator_snapshot,json=initiatorSnapshot,proto3" json:"initiator_snapshot,omitempty"` // client may omit; server overwrites with stored discovery before forwarding
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConnectivityOffer) Reset() {
	*x = ConnectivityOffer{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectivityOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectivityOffer) ProtoMessage() {}

func (x *ConnectivityOffer) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectivityOffer.ProtoReflect.Descriptor instead.
func (*ConnectivityOffer) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{10}
}

func (x *ConnectivityOffer) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ConnectivityOffer) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ConnectivityOffer) GetInitiatorDeviceId() string {
	if x != nil {
		return x.InitiatorDeviceId
	}
	return ""
}

func (x *ConnectivityOffer) GetInitiatorRuntimeEpoch() *RuntimeEpoch {
	if x != nil {
		return x.InitiatorRuntimeEpoch
	}
	return nil
}

func (x *ConnectivityOffer) GetInitiatorRevision() uint32 {
	if x != nil {
		return x.InitiatorRevision
	}
	return 0
}

func (x *ConnectivityOffer) GetInitiatorSnapshot() *DiscoverySnapshot {
	if x != nil {
		return x.InitiatorSnapshot
	}
	return nil
}

type ConnectivityAnswer struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	RequestId             uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // responder's own request id
	AttemptId             string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`  // echoes the offer's attempt_id
	Accepted              bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ResponderDeviceId     string                 `protobuf:"bytes,4,opt,name=responder_device_id,json=responderDeviceId,proto3" json:"responder_device_id,omitempty"`
	ResponderRuntimeEpoch *RuntimeEpoch          `protobuf:"bytes,5,opt,name=responder_runtime_epoch,json=responderRuntimeEpoch,proto3" json:"responder_runtime_epoch,omitempty"`
	ResponderRevision     uint32                 `protobuf:"varint,6,opt,name=responder_revision,json=responderRevision,proto3" json:"responder_revision,omitempty"`
	ResponderSnapshot     *DiscoverySnapshot     `protobuf:"bytes,7,opt,name=responder_snapshot,json=responderSnapshot,proto3" json:"responder_snapshot,omitempty"` // so the initiator learns B's candidates
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ConnectivityAnswer) Reset() {
	*x = ConnectivityAnswer{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectivityAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectivityAnswer) ProtoMessage() {}

func (x *ConnectivityAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectivityAnswer.ProtoReflect.Descriptor instead.
func (*ConnectivityAnswer) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{11}
}

func (x *ConnectivityAnswer) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ConnectivityAnswer) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ConnectivityAnswer) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ConnectivityAnswer) GetResponderDeviceId() string {
	if x != nil {
		return x.ResponderDeviceId
	}
	return ""
}

func (x *ConnectivityAnswer) GetResponderRuntimeEpoch() *RuntimeEpoch {
	if x != nil {
		return x.ResponderRuntimeEpoch
	}
	return nil
}

func (x *ConnectivityAnswer) GetResponderRevision() uint32 {
	if x != nil {
		return x.ResponderRevision
	}
	return 0
}

func (x *ConnectivityAnswer) GetResponderSnapshot() *DiscoverySnapshot {
	if x != nil {
		return x.ResponderSnapshot
	}
	return nil
}

type PresenceHintSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerPresenceHint    `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"` // advisory only; UI cache
	PublishedAtMs int64                  `protobuf:"varint,2,opt,name=published_at_ms,json=publishedAtMs,proto3" json:"published_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceHintSnapshot) Reset() {
	*x = PresenceHintSnapshot{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceHintSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceHintSnapshot) ProtoMessage() {}

func (x *PresenceHintSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceHintSnapshot.ProtoReflect.Descriptor instead.
func (*PresenceHintSnapshot) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{12}
}

func (x *PresenceHintSnapshot) GetPeers() []*PeerPresenceHint {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PresenceHintSnapshot) GetPublishedAtMs() int64 {
	if x != nil {
		return x.PublishedAtMs
	}
	return 0
}

type PeerPresenceHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Online        bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	RuntimeEpoch  *RuntimeEpoch          `protobuf:"bytes,3,opt,name=runtime_epoch,json=runtimeEpoch,proto3" json:"runtime_epoch,omitempty"`
	Revision      uint32                 `protobuf:"varint,4,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerPresenceHint) Reset() {
	*x = PeerPresenceHint{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerPresenceHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerPresenceHint) ProtoMessage() {}

func (x *PeerPresenceHint) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerPresenceHint.ProtoReflect.Descriptor instead.
func (*PeerPresenceHint) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{13}
}

func (x *PeerPresenceHint) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PeerPresenceHint) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *PeerPresenceHint) GetRuntimeEpoch() *RuntimeEpoch {
	if x != nil {
		return x.RuntimeEpoch
	}
	return nil
}

func (x *PeerPresenceHint) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type PeerAvailableHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RuntimeEpoch  *RuntimeEpoch          `protobuf:"bytes,2,opt,name=runtime_epoch,json=runtimeEpoch,proto3" json:"runtime_epoch,omitempty"`
	Revision      uint32                 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerAvailableHint) Reset() {
	*x = PeerAvailableHint{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerAvailableHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerAvailableHint) ProtoMessage() {}

func (x *PeerAvailableHint) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerAvailableHint.ProtoReflect.Descriptor instead.
func (*PeerAvailableHint) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{14}
}

func (x *PeerAvailableHint) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PeerAvailableHint) GetRuntimeEpoch() *RuntimeEpoch {
	if x != nil {
		return x.RuntimeEpoch
	}
	return nil
}

func (x *PeerAvailableHint) GetRevision() uint32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type PeerUnavailableHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerUnavailableHint) Reset() {
	*x = PeerUnavailableHint{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerUnavailableHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerUnavailableHint) ProtoMessage() {}

func (x *PeerUnavailableHint) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerUnavailableHint.ProtoReflect.Descriptor instead.
func (*PeerUnavailableHint) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{15}
}

func (x *PeerUnavailableHint) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PeerUnavailableHint) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RelayReserveRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AttemptId        string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	TargetDeviceId   string                 `protobuf:"bytes,3,opt,name=target_device_id,json=targetDeviceId,proto3" json:"target_device_id,omitempty"`
	DesiredLifetimeS uint32                 `protobuf:"varint,4,opt,name=desired_lifetime_s,json=desiredLifetimeS,proto3" json:"desired_lifetime_s,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RelayReserveRequest) Reset() {
	*x = RelayReserveRequest{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayReserveRequest) ProtoMessage() {}

func (x *RelayReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayReserveRequest.ProtoReflect.Descriptor instead.
func (*RelayReserveRequest) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{16}
}

func (x *RelayReserveRequest) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RelayReserveRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *RelayReserveRequest) GetTargetDeviceId() string {
	if x != nil {
		return x.TargetDeviceId
	}
	return ""
}

func (x *RelayReserveRequest) GetDesiredLifetimeS() uint32 {
	if x != nil {
		return x.DesiredLifetimeS
	}
	return 0
}

type RelayReserveResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AttemptId         string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ReservationId     string                 `protobuf:"bytes,3,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`               // 16-byte hex, 32 chars
	RelayDataEndpoint string                 `protobuf:"bytes,4,opt,name=relay_data_endpoint,json=relayDataEndpoint,proto3" json:"relay_data_endpoint,omitempty"` // self-contained wss://<host>/v2/relay/<reservation_id>
	ExpiresAtMs       int64                  `protobuf:"varint,5,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	LocalToken        []byte                 `protobuf:"bytes,6,opt,name=local_token,json=localToken,proto3" json:"local_token,omitempty"` // 32-byte random, THIS side's connect credential
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RelayReserveResponse) Reset() {
	*x = RelayReserveResponse{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayReserveResponse) ProtoMessage() {}

func (x *RelayReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayReserveResponse.ProtoReflect.Descriptor instead.
func (*RelayReserveResponse) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{17}
}

func (x *RelayReserveResponse) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RelayReserveResponse) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *RelayReserveResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *RelayReserveResponse) GetRelayDataEndpoint() string {
	if x != nil {
		return x.RelayDataEndpoint
	}
	return ""
}

func (x *RelayReserveResponse) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

func (x *RelayReserveResponse) GetLocalToken() []byte {
	if x != nil {
		return x.LocalToken
	}
	return nil
}

type IncomingRelayReservation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AttemptId         string                 `protobuf:"bytes,1,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ReservationId     string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	InitiatorDeviceId string                 `protobuf:"bytes,3,opt,name=initiator_device_id,json=initiatorDeviceId,proto3" json:"initiator_device_id,omitempty"`
	RelayDataEndpoint string                 `protobuf:"bytes,4,opt,name=relay_data_endpoint,json=relayDataEndpoint,proto3" json:"relay_data_endpoint,omitempty"`
	ExpiresAtMs       int64                  `protobuf:"varint,5,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	LocalToken        []byte                 `protobuf:"bytes,6,opt,name=local_token,json=localToken,proto3" json:"local_token,omitempty"` // receiver-specific token (different from initiator's)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IncomingRelayReservation) Reset() {
	*x = IncomingRelayReservation{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingRelayReservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingRelayReservation) ProtoMessage() {}

func (x *IncomingRelayReservation) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingRelayReservation.ProtoReflect.Descriptor instead.
func (*IncomingRelayReservation) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{18}
}

func (x *IncomingRelayReservation) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *IncomingRelayReservation) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *IncomingRelayReservation) GetInitiatorDeviceId() string {
	if x != nil {
		return x.InitiatorDeviceId
	}
	return ""
}

func (x *IncomingRelayReservation) GetRelayDataEndpoint() string {
	if x != nil {
		return x.RelayDataEndpoint
	}
	return ""
}

func (x *IncomingRelayReservation) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

func (x *IncomingRelayReservation) GetLocalToken() []byte {
	if x != nil {
		return x.LocalToken
	}
	return nil
}

type RealtimeSignal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	RealtimeId     string                 `protobuf:"bytes,2,opt,name=realtime_id,json=realtimeId,proto3" json:"realtime_id,omitempty"`
	TargetDeviceId string                 `protobuf:"bytes,3,opt,name=target_device_id,json=targetDeviceId,proto3" json:"target_device_id,omitempty"`
	Kind           RealtimeSignalKind     `protobuf:"varint,4,opt,name=kind,proto3,enum=relay.v2.RealtimeSignalKind" json:"kind,omitempty"`
	Revision       uint64                 `protobuf:"varint,5,opt,name=revision,proto3" json:"revision,omitempty"`
	Payload        []byte                 `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"` // <= 256 KiB
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RealtimeSignal) Reset() {
	*x = RealtimeSignal{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeSignal) ProtoMessage() {}

func (x *RealtimeSignal) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeSignal.ProtoReflect.Descriptor instead.
func (*RealtimeSignal) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{19}
}

func (x *RealtimeSignal) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *RealtimeSignal) GetRealtimeId() string {
	if x != nil {
		return x.RealtimeId
	}
	return ""
}

func (x *RealtimeSignal) GetTargetDeviceId() string {
	if x != nil {
		return x.TargetDeviceId
	}
	return ""
}

func (x *RealtimeSignal) GetKind() RealtimeSignalKind {
	if x != nil {
		return x.Kind
	}
	return RealtimeSignalKind_REALTIME_SIGNAL_KIND_UNSPECIFIED
}

func (x *RealtimeSignal) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *RealtimeSignal) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ProtocolError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // echoes the failing request; 0 = server-initiated
	AttemptId     string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`  // set when the error belongs to an async attempt
	Code          ErrorCode              `protobuf:"varint,3,opt,name=code,proto3,enum=relay.v2.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolError) Reset() {
	*x = ProtocolError{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolError) ProtoMessage() {}

func (x *ProtocolError) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolError.ProtoReflect.Descriptor instead.
func (*ProtocolError) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{20}
}

func (x *ProtocolError) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ProtocolError) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *ProtocolError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *ProtocolError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RelayFrame struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // must be 2
	// Types that are valid to be assigned to Kind:
	//
	//	*RelayFrame_Ready
	//	*RelayFrame_Heartbeat
	//	*RelayFrame_HeartbeatAck
	//	*RelayFrame_DiscoveryPublish
	//	*RelayFrame_DiscoveryAck
	//	*RelayFrame_ResolvePeerRequest
	//	*RelayFrame_ResolvePeerResponse
	//	*RelayFrame_ConnectivityOffer
	//	*RelayFrame_ConnectivityAnswer
	//	*RelayFrame_PresenceHintSnapshot
	//	*RelayFrame_PeerAvailableHint
	//	*RelayFrame_PeerUnavailableHint
	//	*RelayFrame_RelayReserveRequest
	//	*RelayFrame_RelayReserveResponse
	//	*RelayFrame_IncomingRelayReservation
	//	*RelayFrame_RealtimeSignal
	//	*RelayFrame_ProtocolError
	Kind          isRelayFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayFrame) Reset() {
	*x = RelayFrame{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayFrame) ProtoMessage() {}

func (x *RelayFrame) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayFrame.ProtoReflect.Descriptor instead.
func (*RelayFrame) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{21}
}

func (x *RelayFrame) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RelayFrame) GetKind() isRelayFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RelayFrame) GetReady() *Ready {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *RelayFrame) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *RelayFrame) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *RelayFrame) GetDiscoveryPublish() *DiscoveryPublish {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_DiscoveryPublish); ok {
			return x.DiscoveryPublish
		}
	}
	return nil
}

func (x *RelayFrame) GetDiscoveryAck() *DiscoveryAck {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_DiscoveryAck); ok {
			return x.DiscoveryAck
		}
	}
	return nil
}

func (x *RelayFrame) GetResolvePeerRequest() *ResolvePeerRequest {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_ResolvePeerRequest); ok {
			return x.ResolvePeerRequest
		}
	}
	return nil
}

func (x *RelayFrame) GetResolvePeerResponse() *ResolvePeerResponse {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_ResolvePeerResponse); ok {
			return x.ResolvePeerResponse
		}
	}
	return nil
}

func (x *RelayFrame) GetConnectivityOffer() *ConnectivityOffer {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_ConnectivityOffer); ok {
			return x.ConnectivityOffer
		}
	}
	return nil
}

func (x *RelayFrame) GetConnectivityAnswer() *ConnectivityAnswer {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_ConnectivityAnswer); ok {
			return x.ConnectivityAnswer
		}
	}
	return nil
}

func (x *RelayFrame) GetPresenceHintSnapshot() *PresenceHintSnapshot {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_PresenceHintSnapshot); ok {
			return x.PresenceHintSnapshot
		}
	}
	return nil
}

func (x *RelayFrame) GetPeerAvailableHint() *PeerAvailableHint {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_PeerAvailableHint); ok {
			return x.PeerAvailableHint
		}
	}
	return nil
}

func (x *RelayFrame) GetPeerUnavailableHint() *PeerUnavailableHint {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_PeerUnavailableHint); ok {
			return x.PeerUnavailableHint
		}
	}
	return nil
}

func (x *RelayFrame) GetRelayReserveRequest() *RelayReserveRequest {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_RelayReserveRequest); ok {
			return x.RelayReserveRequest
		}
	}
	return nil
}

func (x *RelayFrame) GetRelayReserveResponse() *RelayReserveResponse {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_RelayReserveResponse); ok {
			return x.RelayReserveResponse
		}
	}
	return nil
}

func (x *RelayFrame) GetIncomingRelayReservation() *IncomingRelayReservation {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_IncomingRelayReservation); ok {
			return x.IncomingRelayReservation
		}
	}
	return nil
}

func (x *RelayFrame) GetRealtimeSignal() *RealtimeSignal {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_RealtimeSignal); ok {
			return x.RealtimeSignal
		}
	}
	return nil
}

func (x *RelayFrame) GetProtocolError() *ProtocolError {
	if x != nil {
		if x, ok := x.Kind.(*RelayFrame_ProtocolError); ok {
			return x.ProtocolError
		}
	}
	return nil
}

type isRelayFrame_Kind interface {
	isRelayFrame_Kind()
}

type RelayFrame_Ready struct {
	Ready *Ready `protobuf:"bytes,10,opt,name=ready,proto3,oneof"`
}

type RelayFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type RelayFrame_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,12,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type RelayFrame_DiscoveryPublish struct {
	DiscoveryPublish *DiscoveryPublish `protobuf:"bytes,13,opt,name=discovery_publish,json=discoveryPublish,proto3,oneof"`
}

type RelayFrame_DiscoveryAck struct {
	DiscoveryAck *DiscoveryAck `protobuf:"bytes,14,opt,name=discovery_ack,json=discoveryAck,proto3,oneof"`
}

type RelayFrame_ResolvePeerRequest struct {
	ResolvePeerRequest *ResolvePeerRequest `protobuf:"bytes,15,opt,name=resolve_peer_request,json=resolvePeerRequest,proto3,oneof"`
}

type RelayFrame_ResolvePeerResponse struct {
	ResolvePeerResponse *ResolvePeerResponse `protobuf:"bytes,16,opt,name=resolve_peer_response,json=resolvePeerResponse,proto3,oneof"`
}

type RelayFrame_ConnectivityOffer struct {
	ConnectivityOffer *ConnectivityOffer `protobuf:"bytes,17,opt,name=connectivity_offer,json=connectivityOffer,proto3,oneof"`
}

type RelayFrame_ConnectivityAnswer struct {
	ConnectivityAnswer *ConnectivityAnswer `protobuf:"bytes,18,opt,name=connectivity_answer,json=connectivityAnswer,proto3,oneof"`
}

type RelayFrame_PresenceHintSnapshot struct {
	PresenceHintSnapshot *PresenceHintSnapshot `protobuf:"bytes,19,opt,name=presence_hint_snapshot,json=presenceHintSnapshot,proto3,oneof"`
}

type RelayFrame_PeerAvailableHint struct {
	PeerAvailableHint *PeerAvailableHint `protobuf:"bytes,20,opt,name=peer_available_hint,json=peerAvailableHint,proto3,oneof"`
}

type RelayFrame_PeerUnavailableHint struct {
	PeerUnavailableHint *PeerUnavailableHint `protobuf:"bytes,21,opt,name=peer_unavailable_hint,json=peerUnavailableHint,proto3,oneof"`
}

type RelayFrame_RelayReserveRequest struct {
	RelayReserveRequest *RelayReserveRequest `protobuf:"bytes,22,opt,name=relay_reserve_request,json=relayReserveRequest,proto3,oneof"`
}

type RelayFrame_RelayReserveResponse struct {
	RelayReserveResponse *RelayReserveResponse `protobuf:"bytes,23,opt,name=relay_reserve_response,json=relayReserveResponse,proto3,oneof"`
}

type RelayFrame_IncomingRelayReservation struct {
	IncomingRelayReservation *IncomingRelayReservation `protobuf:"bytes,24,opt,name=incoming_relay_reservation,json=incomingRelayReservation,proto3,oneof"`
}

type RelayFrame_RealtimeSignal struct {
	RealtimeSignal *RealtimeSignal `protobuf:"bytes,25,opt,name=realtime_signal,json=realtimeSignal,proto3,oneof"`
}

type RelayFrame_ProtocolError struct {
	ProtocolError *ProtocolError `protobuf:"bytes,26,opt,name=protocol_error,json=protocolError,proto3,oneof"`
}

func (*RelayFrame_Ready) isRelayFrame_Kind() {}

func (*RelayFrame_Heartbeat) isRelayFrame_Kind() {}

func (*RelayFrame_HeartbeatAck) isRelayFrame_Kind() {}

func (*RelayFrame_DiscoveryPublish) isRelayFrame_Kind() {}

func (*RelayFrame_DiscoveryAck) isRelayFrame_Kind() {}

func (*RelayFrame_ResolvePeerRequest) isRelayFrame_Kind() {}

func (*RelayFrame_ResolvePeerResponse) isRelayFrame_Kind() {}

func (*RelayFrame_ConnectivityOffer) isRelayFrame_Kind() {}

func (*RelayFrame_ConnectivityAnswer) isRelayFrame_Kind() {}

func (*RelayFrame_PresenceHintSnapshot) isRelayFrame_Kind() {}

func (*RelayFrame_PeerAvailableHint) isRelayFrame_Kind() {}

func (*RelayFrame_PeerUnavailableHint) isRelayFrame_Kind() {}

func (*RelayFrame_RelayReserveRequest) isRelayFrame_Kind() {}

func (*RelayFrame_RelayReserveResponse) isRelayFrame_Kind() {}

func (*RelayFrame_IncomingRelayReservation) isRelayFrame_Kind() {}

func (*RelayFrame_RealtimeSignal) isRelayFrame_Kind() {}

func (*RelayFrame_ProtocolError) isRelayFrame_Kind() {}

type RelayDataFrame struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // must be 2
	// Types that are valid to be assigned to Kind:
	//
	//	*RelayDataFrame_Connect
	//	*RelayDataFrame_Payload
	//	*RelayDataFrame_Ack
	//	*RelayDataFrame_Close
	Kind          isRelayDataFrame_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayDataFrame) Reset() {
	*x = RelayDataFrame{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayDataFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayDataFrame) ProtoMessage() {}

func (x *RelayDataFrame) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayDataFrame.ProtoReflect.Descriptor instead.
func (*RelayDataFrame) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{22}
}

func (x *RelayDataFrame) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RelayDataFrame) GetKind() isRelayDataFrame_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RelayDataFrame) GetConnect() *RelayDataConnect {
	if x != nil {
		if x, ok := x.Kind.(*RelayDataFrame_Connect); ok {
			return x.Connect
		}
	}
	return nil
}

func (x *RelayDataFrame) GetPayload() *RelayDataPayload {
	if x != nil {
		if x, ok := x.Kind.(*RelayDataFrame_Payload); ok {
			return x.Payload
		}
	}
	return nil
}

func (x *RelayDataFrame) GetAck() *RelayDataAck {
	if x != nil {
		if x, ok := x.Kind.(*RelayDataFrame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *RelayDataFrame) GetClose() *RelayDataClose {
	if x != nil {
		if x, ok := x.Kind.(*RelayDataFrame_Close); ok {
			return x.Close
		}
	}
	return nil
}

type isRelayDataFrame_Kind interface {
	isRelayDataFrame_Kind()
}

type RelayDataFrame_Connect struct {
	Connect *RelayDataConnect `protobuf:"bytes,10,opt,name=connect,proto3,oneof"`
}

type RelayDataFrame_Payload struct {
	Payload *RelayDataPayload `protobuf:"bytes,11,opt,name=payload,proto3,oneof"`
}

type RelayDataFrame_Ack struct {
	Ack *RelayDataAck `protobuf:"bytes,12,opt,name=ack,proto3,oneof"`
}

type RelayDataFrame_Close struct {
	Close *RelayDataClose `protobuf:"bytes,13,opt,name=close,proto3,oneof"`
}

func (*RelayDataFrame_Connect) isRelayDataFrame_Kind() {}

func (*RelayDataFrame_Payload) isRelayDataFrame_Kind() {}

func (*RelayDataFrame_Ack) isRelayDataFrame_Kind() {}

func (*RelayDataFrame_Close) isRelayDataFrame_Kind() {}

type RelayDataConnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"` // must equal the path segment
	LocalToken    []byte                 `protobuf:"bytes,2,opt,name=local_token,json=localToken,proto3" json:"local_token,omitempty"`          // must match the reservation-side token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayDataConnect) Reset() {
	*x = RelayDataConnect{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayDataConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayDataConnect) ProtoMessage() {}

func (x *RelayDataConnect) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayDataConnect.ProtoReflect.Descriptor instead.
func (*RelayDataConnect) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{23}
}

func (x *RelayDataConnect) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *RelayDataConnect) GetLocalToken() []byte {
	if x != nil {
		return x.LocalToken
	}
	return nil
}

type RelayDataPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Sequence         uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`                                        // monotonic per direction
	EncryptedPayload []byte                 `protobuf:"bytes,2,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"` // opaque; relay never decrypts or parses
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RelayDataPayload) Reset() {
	*x = RelayDataPayload{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayDataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayDataPayload) ProtoMessage() {}

func (x *RelayDataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayDataPayload.ProtoReflect.Descriptor instead.
func (*RelayDataPayload) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{24}
}

func (x *RelayDataPayload) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *RelayDataPayload) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

type RelayDataAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"` // receipt / flow-control echo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayDataAck) Reset() {
	*x = RelayDataAck{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayDataAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayDataAck) ProtoMessage() {}

func (x *RelayDataAck) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayDataAck.ProtoReflect.Descriptor instead.
func (*RelayDataAck) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{25}
}

func (x *RelayDataAck) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type RelayDataClose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        uint32                 `protobuf:"varint,1,opt,name=reason,proto3" json:"reason,omitempty"` // 0 normal, 1 expiry, 2 error
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayDataClose) Reset() {
	*x = RelayDataClose{}
	mi := &file_relay_v2_relay_v2_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayDataClose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayDataClose) ProtoMessage() {}

func (x *RelayDataClose) ProtoReflect() protoreflect.Message {
	mi := &file_relay_v2_relay_v2_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayDataClose.ProtoReflect.Descriptor instead.
func (*RelayDataClose) Descriptor() ([]byte, []int) {
	return file_relay_v2_relay_v2_proto_rawDescGZIP(), []int{26}
}

func (x *RelayDataClose) GetReason() uint32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

func (x *RelayDataClose) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_relay_v2_relay_v2_proto protoreflect.FileDescriptor

const file_relay_v2_relay_v2_proto_rawDesc = "" +
	"\n" +
	"\x17relay/v2/relay_v2.proto\x12\brelay.v2\"4\n" +
	"\fRuntimeEpoch\x12\x12\n" +
	"\x04high\x18\x01 \x01(\x06R\x04high\x12\x10\n" +
	"\x03low\x18\x02 \x01(\x06R\x03low\"1\n" +
	"\x0fCandidateBundle\x12\x1e\n" +
	"\n" +
	"candidates\x18\x01 \x03(\fR\n" +
	"candidates\"\xb0\x02\n" +
	"\x11DiscoverySnapshot\x12;\n" +
	"\rruntime_epoch\x18\x01 \x01(\v2\x16.relay.v2.RuntimeEpochR\fruntimeEpoch\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\rR\brevision\x12T\n" +
	"\x16transport_capabilities\x18\x03 \x03(\x0e2\x1d.relay.v2.TransportCapabilityR\x15transportCapabilities\x12D\n" +
	"\x10candidate_bundle\x18\x04 \x01(\v2\x19.relay.v2.CandidateBundleR\x0fcandidateBundle\x12&\n" +
	"\x0fpublished_at_ms\x18\x05 \x01(\x03R\rpublishedAtMs\"\xcd\x01\n" +
	"\x05Ready\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12$\n" +
	"\x0eserver_time_ms\x18\x03 \x01(\x03R\fserverTimeMs\x120\n" +
	"\x14heartbeat_interval_s\x18\x04 \x01(\rR\x12heartbeatIntervalS\x12$\n" +
	"\x0epresence_ttl_s\x18\x05 \x01(\rR\fpresenceTtlS\"H\n" +
	"\tHeartbeat\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1c\n" +
	"\n" +
	"sent_at_ms\x18\x02 \x01(\x03R\bsentAtMs\"S\n" +
	"\fHeartbeatAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12$\n" +
	"\x0eserver_time_ms\x18\x02 \x01(\x03R\fserverTimeMs\"j\n" +
	"\x10DiscoveryPublish\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x127\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x1b.relay.v2.DiscoverySnapshotR\bsnapshot\"\x86\x01\n" +
	"\fDiscoveryAck\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12;\n" +
	"\rruntime_epoch\x18\x02 \x01(\v2\x16.relay.v2.RuntimeEpochR\fruntimeEpoch\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\rR\brevision\"]\n" +
	"\x12ResolvePeerRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12(\n" +
	"\x10target_device_id\x18\x02 \x01(\tR\x0etargetDeviceId\"\xc6\x01\n" +
	"\x13ResolvePeerResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.relay.v2.ResolveStatusR\x06status\x129\n" +
	"\tdiscovery\x18\x03 \x01(\v2\x1b.relay.v2.DiscoverySnapshotR\tdiscovery\x12$\n" +
	"\x0eretry_after_ms\x18\x04 \x01(\rR\fretryAfterMs\"\xcc\x02\n" +
	"\x11ConnectivityOffer\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12.\n" +
	"\x13initiator_device_id\x18\x03 \x01(\tR\x11initiatorDeviceId\x12N\n" +
	"\x17initiator_runtime_epoch\x18\x04 \x01(\v2\x16.relay.v2.RuntimeEpochR\x15initiatorRuntimeEpoch\x12-\n" +
	"\x12initiator_revision\x18\x05 \x01(\rR\x11initiatorRevision\x12J\n" +
	"\x12initiator_snapshot\x18\x06 \x01(\v2\x1b.relay.v2.DiscoverySnapshotR\x11initiatorSnapshot\"\xe9\x02\n" +
	"\x12ConnectivityAnswer\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12.\n" +
	"\x13responder_device_id\x18\x04 \x01(\tR\x11responderDeviceId\x12N\n" +
	"\x17responder_runtime_epoch\x18\x05 \x01(\v2\x16.relay.v2.RuntimeEpochR\x15responderRuntimeEpoch\x12-\n" +
	"\x12responder_revision\x18\x06 \x01(\rR\x11responderRevision\x12J\n" +
	"\x12responder_snapshot\x18\a \x01(\v2\x1b.relay.v2.DiscoverySnapshotR\x11responderSnapshot\"p\n" +
	"\x14PresenceHintSnapshot\x120\n" +
	"\x05peers\x18\x01 \x03(\v2\x1a.relay.v2.PeerPresenceHintR\x05peers\x12&\n" +
	"\x0fpublished_at_ms\x18\x02 \x01(\x03R\rpublishedAtMs\"\xa0\x01\n" +
	"\x10PeerPresenceHint\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x12;\n" +
	"\rruntime_epoch\x18\x03 \x01(\v2\x16.relay.v2.RuntimeEpochR\fruntimeEpoch\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\rR\brevision\"\x89\x01\n" +
	"\x11PeerAvailableHint\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12;\n" +
	"\rruntime_epoch\x18\x02 \x01(\v2\x16.relay.v2.RuntimeEpochR\fruntimeEpoch\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\rR\brevision\"J\n" +
	"\x13PeerUnavailableHint\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xab\x01\n" +
	"\x13RelayReserveRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12(\n" +
	"\x10target_device_id\x18\x03 \x01(\tR\x0etargetDeviceId\x12,\n" +
	"\x12desired_lifetime_s\x18\x04 \x01(\rR\x10desiredLifetimeS\"\xf0\x01\n" +
	"\x14RelayReserveResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12%\n" +
	"\x0ereservation_id\x18\x03 \x01(\tR\rreservationId\x12.\n" +
	"\x13relay_data_endpoint\x18\x04 \x01(\tR\x11relayDataEndpoint\x12\"\n" +
	"\rexpires_at_ms\x18\x05 \x01(\x03R\vexpiresAtMs\x12\x1f\n" +
	"\vlocal_token\x18\x06 \x01(\fR\n" +
	"localToken\"\x85\x02\n" +
	"\x18IncomingRelayReservation\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x01 \x01(\tR\tattemptId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12.\n" +
	"\x13initiator_device_id\x18\x03 \x01(\tR\x11initiatorDeviceId\x12.\n" +
	"\x13relay_data_endpoint\x18\x04 \x01(\tR\x11relayDataEndpoint\x12\"\n" +
	"\rexpires_at_ms\x18\x05 \x01(\x03R\vexpiresAtMs\x12\x1f\n" +
	"\vlocal_token\x18\x06 \x01(\fR\n" +
	"localToken\"\xe2\x01\n" +
	"\x0eRealtimeSignal\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1f\n" +
	"\vrealtime_id\x18\x02 \x01(\tR\n" +
	"realtimeId\x12(\n" +
	"\x10target_device_id\x18\x03 \x01(\tR\x0etargetDeviceId\x120\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x1c.relay.v2.RealtimeSignalKindR\x04kind\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\x04R\brevision\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"\x90\x01\n" +
	"\rProtocolError\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12'\n" +
	"\x04code\x18\x03 \x01(\x0e2\x13.relay.v2.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xb5\n" +
	"\n" +
	"\n" +
	"RelayFrame\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12'\n" +
	"\x05ready\x18\n" +
	" \x01(\v2\x0f.relay.v2.ReadyH\x00R\x05ready\x123\n" +
	"\theartbeat\x18\v \x01(\v2\x13.relay.v2.HeartbeatH\x00R\theartbeat\x12=\n" +
	"\rheartbeat_ack\x18\f \x01(\v2\x16.relay.v2.HeartbeatAckH\x00R\fheartbeatAck\x12I\n" +
	"\x11discovery_publish\x18\r \x01(\v2\x1a.relay.v2.DiscoveryPublishH\x00R\x10discoveryPublish\x12=\n" +
	"\rdiscovery_ack\x18\x0e \x01(\v2\x16.relay.v2.DiscoveryAckH\x00R\fdiscoveryAck\x12P\n" +
	"\x14resolve_peer_request\x18\x0f \x01(\v2\x1c.relay.v2.ResolvePeerRequestH\x00R\x12resolvePeerRequest\x12S\n" +
	"\x15resolve_peer_response\x18\x10 \x01(\v2\x1d.relay.v2.ResolvePeerResponseH\x00R\x13resolvePeerResponse\x12L\n" +
	"\x12connectivity_offer\x18\x11 \x01(\v2\x1b.relay.v2.ConnectivityOfferH\x00R\x11connectivityOffer\x12O\n" +
	"\x13connectivity_answer\x18\x12 \x01(\v2\x1c.relay.v2.ConnectivityAnswerH\x00R\x12connectivityAnswer\x12V\n" +
	"\x16presence_hint_snapshot\x18\x13 \x01(\v2\x1e.relay.v2.PresenceHintSnapshotH\x00R\x14presenceHintSnapshot\x12M\n" +
	"\x13peer_available_hint\x18\x14 \x01(\v2\x1b.relay.v2.PeerAvailableHintH\x00R\x11peerAvailableHint\x12S\n" +
	"\x15peer_unavailable_hint\x18\x15 \x01(\v2\x1d.relay.v2.PeerUnavailableHintH\x00R\x13peerUnavailableHint\x12S\n" +
	"\x15relay_reserve_request\x18\x16 \x01(\v2\x1d.relay.v2.RelayReserveRequestH\x00R\x13relayReserveRequest\x12V\n" +
	"\x16relay_reserve_response\x18\x17 \x01(\v2\x1e.relay.v2.RelayReserveResponseH\x00R\x14relayReserveResponse\x12b\n" +
	"\x1aincoming_relay_reservation\x18\x18 \x01(\v2\".relay.v2.IncomingRelayReservationH\x00R\x18incomingRelayReservation\x12C\n" +
	"\x0frealtime_signal\x18\x19 \x01(\v2\x18.relay.v2.RealtimeSignalH\x00R\x0erealtimeSignal\x12@\n" +
	"\x0eprotocol_error\x18\x1a \x01(\v2\x17.relay.v2.ProtocolErrorH\x00R\rprotocolErrorB\x06\n" +
	"\x04kindJ\x04\b\x1e\x10@\"\x86\x02\n" +
	"\x0eRelayDataFrame\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x126\n" +
	"\aconnect\x18\n" +
	" \x01(\v2\x1a.relay.v2.RelayDataConnectH\x00R\aconnect\x126\n" +
	"\apayload\x18\v \x01(\v2\x1a.relay.v2.RelayDataPayloadH\x00R\apayload\x12*\n" +
	"\x03ack\x18\f \x01(\v2\x16.relay.v2.RelayDataAckH\x00R\x03ack\x120\n" +
	"\x05close\x18\r \x01(\v2\x18.relay.v2.RelayDataCloseH\x00R\x05closeB\x06\n" +
	"\x04kindJ\x04\b\x1e\x10@\"Z\n" +
	"\x10RelayDataConnect\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1f\n" +
	"\vlocal_token\x18\x02 \x01(\fR\n" +
	"localToken\"[\n" +
	"\x10RelayDataPayload\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12+\n" +
	"\x11encrypted_payload\x18\x02 \x01(\fR\x10encryptedPayload\"*\n" +
	"\fRelayDataAck\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\"@\n" +
	"\x0eRelayDataClose\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\rR\x06reason\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail*\x89\x02\n" +
	"\x13TransportCapability\x12$\n" +
	" TRANSPORT_CAPABILITY_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19TRANSPORT_CAPABILITY_QUIC\x10\x01\x12\x1c\n" +
	"\x18TRANSPORT_CAPABILITY_TCP\x10\x02\x12%\n" +
	"!TRANSPORT_CAPABILITY_UDP_DATAGRAM\x10\x03\x12\"\n" +
	"\x1eTRANSPORT_CAPABILITY_WEBSOCKET\x10\x04\x12\x1f\n" +
	"\x1bTRANSPORT_CAPABILITY_WEBRTC\x10\x05\x12#\n" +
	"\x1fTRANSPORT_CAPABILITY_RELAY_DATA\x10\x06*\x9f\x01\n" +
	"\rResolveStatus\x12\x1e\n" +
	"\x1aRESOLVE_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14RESOLVE_STATUS_READY\x10\x01\x12\x1a\n" +
	"\x16RESOLVE_STATUS_OFFLINE\x10\x02\x12\x1c\n" +
	"\x18RESOLVE_STATUS_NOT_READY\x10\x03\x12\x1a\n" +
	"\x16RESOLVE_STATUS_UNKNOWN\x10\x04*\xe9\x01\n" +
	"\x12RealtimeSignalKind\x12$\n" +
	" REALTIME_SIGNAL_KIND_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aREALTIME_SIGNAL_KIND_OFFER\x10\x01\x12\x1f\n" +
	"\x1bREALTIME_SIGNAL_KIND_ANSWER\x10\x02\x12&\n" +
	"\"REALTIME_SIGNAL_KIND_ICE_CANDIDATE\x10\x03\x12$\n" +
	" REALTIME_SIGNAL_KIND_ICE_RESTART\x10\x04\x12\x1e\n" +
	"\x1aREALTIME_SIGNAL_KIND_CLOSE\x10\x05*\xea\x03\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eERROR_CODE_CONTROL_UNAVAILABLE\x10\x01\x12$\n" +
	" ERROR_CODE_AUTHENTICATION_FAILED\x10\x02\x12\x1b\n" +
	"\x17ERROR_CODE_PEER_OFFLINE\x10\x03\x12\x1d\n" +
	"\x19ERROR_CODE_PEER_NOT_READY\x10\x04\x12\x1e\n" +
	"\x1aERROR_CODE_RESOLVE_TIMEOUT\x10\x05\x12\x17\n" +
	"\x13ERROR_CODE_PROTOCOL\x10\x06\x12\x1d\n" +
	"\x19ERROR_CODE_EPOCH_CONFLICT\x10\a\x12\x1d\n" +
	"\x19ERROR_CODE_REVISION_STALE\x10\b\x12!\n" +
	"\x1dERROR_CODE_RESERVATION_FAILED\x10\t\x12\"\n" +
	"\x1eERROR_CODE_RESERVATION_EXPIRED\x10\n" +
	"\x12 \n" +
	"\x1cERROR_CODE_RELAY_UNAVAILABLE\x10\v\x12\x1b\n" +
	"\x17ERROR_CODE_RATE_LIMITED\x10\f\x12\x1e\n" +
	"\x1aERROR_CODE_MALFORMED_FRAME\x10\r\x12\x1e\n" +
	"\x1aERROR_CODE_FRAME_TOO_LARGE\x10\x0eB2Z0github.com/ssh-mobile/relay/internal/relay/v2;v2b\x06proto3"

var (
	file_relay_v2_relay_v2_proto_rawDescOnce sync.Once
	file_relay_v2_relay_v2_proto_rawDescData []byte
)

func file_relay_v2_relay_v2_proto_rawDescGZIP() []byte {
	file_relay_v2_relay_v2_proto_rawDescOnce.Do(func() {
		file_relay_v2_relay_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relay_v2_relay_v2_proto_rawDesc), len(file_relay_v2_relay_v2_proto_rawDesc)))
	})
	return file_relay_v2_relay_v2_proto_rawDescData
}

var file_relay_v2_relay_v2_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_relay_v2_relay_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_relay_v2_relay_v2_proto_goTypes = []any{
	(TransportCapability)(0),         // 0: relay.v2.TransportCapability
	(ResolveStatus)(0),               // 1: relay.v2.ResolveStatus
	(RealtimeSignalKind)(0),          // 2: relay.v2.RealtimeSignalKind
	(ErrorCode)(0),                   // 3: relay.v2.ErrorCode
	(*RuntimeEpoch)(nil),             // 4: relay.v2.RuntimeEpoch
	(*CandidateBundle)(nil),          // 5: relay.v2.CandidateBundle
	(*DiscoverySnapshot)(nil),        // 6: relay.v2.DiscoverySnapshot
	(*Ready)(nil),                    // 7: relay.v2.Ready
	(*Heartbeat)(nil),                // 8: relay.v2.Heartbeat
	(*HeartbeatAck)(nil),             // 9: relay.v2.HeartbeatAck
	(*DiscoveryPublish)(nil),         // 10: relay.v2.DiscoveryPublish
	(*DiscoveryAck)(nil),             // 11: relay.v2.DiscoveryAck
	(*ResolvePeerRequest)(nil),       // 12: relay.v2.ResolvePeerRequest
	(*ResolvePeerResponse)(nil),      // 13: relay.v2.ResolvePeerResponse
	(*ConnectivityOffer)(nil),        // 14: relay.v2.ConnectivityOffer
	(*ConnectivityAnswer)(nil),       // 15: relay.v2.ConnectivityAnswer
	(*PresenceHintSnapshot)(nil),     // 16: relay.v2.PresenceHintSnapshot
	(*PeerPresenceHint)(nil),         // 17: relay.v2.PeerPresenceHint
	(*PeerAvailableHint)(nil),        // 18: relay.v2.PeerAvailableHint
	(*PeerUnavailableHint)(nil),      // 19: relay.v2.PeerUnavailableHint
	(*RelayReserveRequest)(nil),      // 20: relay.v2.RelayReserveRequest
	(*RelayReserveResponse)(nil),     // 21: relay.v2.RelayReserveResponse
	(*IncomingRelayReservation)(nil), // 22: relay.v2.IncomingRelayReservation
	(*RealtimeSignal)(nil),           // 23: relay.v2.RealtimeSignal
	(*ProtocolError)(nil),            // 24: relay.v2.ProtocolError
	(*RelayFrame)(nil),               // 25: relay.v2.RelayFrame
	(*RelayDataFrame)(nil),           // 26: relay.v2.RelayDataFrame
	(*RelayDataConnect)(nil),         // 27: relay.v2.RelayDataConnect
	(*RelayDataPayload)(nil),         // 28: relay.v2.RelayDataPayload
	(*RelayDataAck)(nil),             // 29: relay.v2.RelayDataAck
	(*RelayDataClose)(nil),           // 30: relay.v2.RelayDataClose
}
var file_relay_v2_relay_v2_proto_depIdxs = []int32{
	4,  // 0: relay.v2.DiscoverySnapshot.runtime_epoch:type_name -> relay.v2.RuntimeEpoch
	0,  // 1: relay.v2.DiscoverySnapshot.transport_capabilities:type_name -> relay.v2.TransportCapability
	5,  // 2: relay.v2.DiscoverySnapshot.candidate_bundle:type_name -> relay.v2.CandidateBundle
	6,  // 3: relay.v2.DiscoveryPublish.snapshot:type_name -> relay.v2.DiscoverySnapshot
	4,  // 4: relay.v2.DiscoveryAck.runtime_epoch:type_name -> relay.v2.RuntimeEpoch
	1,  // 5: relay.v2.ResolvePeerResponse.status:type_name -> relay.v2.ResolveStatus
	6,  // 6: relay.v2.ResolvePeerResponse.discovery:type_name -> relay.v2.DiscoverySnapshot
	4,  // 7: relay.v2.ConnectivityOffer.initiator_runtime_epoch:type_name -> relay.v2.RuntimeEpoch
	6,  // 8: relay.v2.ConnectivityOffer.initiator_snapshot:type_name -> relay.v2.DiscoverySnapshot
	4,  // 9: relay.v2.ConnectivityAnswer.responder_runtime_epoch:type_name -> relay.v2.RuntimeEpoch
	6,  // 10: relay.v2.ConnectivityAnswer.responder_snapshot:type_name -> relay.v2.DiscoverySnapshot
	17, // 11: relay.v2.PresenceHintSnapshot.peers:type_name -> relay.v2.PeerPresenceHint
	4,  // 12: relay.v2.PeerPresenceHint.runtime_epoch:type_name -> relay.v2.RuntimeEpoch
	4,  // 13: relay.v2.PeerAvailableHint.runtime_epoch:type_name -> relay.v2.RuntimeEpoch
	2,  // 14: relay.v2.RealtimeSignal.kind:type_name -> relay.v2.RealtimeSignalKind
	3,  // 15: relay.v2.ProtocolError.code:type_name -> relay.v2.ErrorCode
	7,  // 16: relay.v2.RelayFrame.ready:type_name -> relay.v2.Ready
	8,  // 17: relay.v2.RelayFrame.heartbeat:type_name -> relay.v2.Heartbeat
	9,  // 18: relay.v2.RelayFrame.heartbeat_ack:type_name -> relay.v2.HeartbeatAck
	10, // 19: relay.v2.RelayFrame.discovery_publish:type_name -> relay.v2.DiscoveryPublish
	11, // 20: relay.v2.RelayFrame.discovery_ack:type_name -> relay.v2.DiscoveryAck
	12, // 21: relay.v2.RelayFrame.resolve_peer_request:type_name -> relay.v2.ResolvePeerRequest
	13, // 22: relay.v2.RelayFrame.resolve_peer_response:type_name -> relay.v2.ResolvePeerResponse
	14, // 23: relay.v2.RelayFrame.connectivity_offer:type_name -> relay.v2.ConnectivityOffer
	15, // 24: relay.v2.RelayFrame.connectivity_answer:type_name -> relay.v2.ConnectivityAnswer
	16, // 25: relay.v2.RelayFrame.presence_hint_snapshot:type_name -> relay.v2.PresenceHintSnapshot
	18, // 26: relay.v2.RelayFrame.peer_available_hint:type_name -> relay.v2.PeerAvailableHint
	19, // 27: relay.v2.RelayFrame.peer_unavailable_hint:type_name -> relay.v2.PeerUnavailableHint
	20, // 28: relay.v2.RelayFrame.relay_reserve_request:type_name -> relay.v2.RelayReserveRequest
	21, // 29: relay.v2.RelayFrame.relay_reserve_response:type_name -> relay.v2.RelayReserveResponse
	22, // 30: relay.v2.RelayFrame.incoming_relay_reservation:type_name -> relay.v2.IncomingRelayReservation
	23, // 31: relay.v2.RelayFrame.realtime_signal:type_name -> relay.v2.RealtimeSignal
	24, // 32: relay.v2.RelayFrame.protocol_error:type_name -> relay.v2.ProtocolError
	27, // 33: relay.v2.RelayDataFrame.connect:type_name -> relay.v2.RelayDataConnect
	28, // 34: relay.v2.RelayDataFrame.payload:type_name -> relay.v2.RelayDataPayload
	29, // 35: relay.v2.RelayDataFrame.ack:type_name -> relay.v2.RelayDataAck
	30, // 36: relay.v2.RelayDataFrame.close:type_name -> relay.v2.RelayDataClose
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_relay_v2_relay_v2_proto_init() }
func file_relay_v2_relay_v2_proto_init() {
	if File_relay_v2_relay_v2_proto != nil {
		return
	}
	file_relay_v2_relay_v2_proto_msgTypes[21].OneofWrappers = []any{
		(*RelayFrame_Ready)(nil),
		(*RelayFrame_Heartbeat)(nil),
		(*RelayFrame_HeartbeatAck)(nil),
		(*RelayFrame_DiscoveryPublish)(nil),
		(*RelayFrame_DiscoveryAck)(nil),
		(*RelayFrame_ResolvePeerRequest)(nil),
		(*RelayFrame_ResolvePeerResponse)(nil),
		(*RelayFrame_ConnectivityOffer)(nil),
		(*RelayFrame_ConnectivityAnswer)(nil),
		(*RelayFrame_PresenceHintSnapshot)(nil),
		(*RelayFrame_PeerAvailableHint)(nil),
		(*RelayFrame_PeerUnavailableHint)(nil),
		(*RelayFrame_RelayReserveRequest)(nil),
		(*RelayFrame_RelayReserveResponse)(nil),
		(*RelayFrame_IncomingRelayReservation)(nil),
		(*RelayFrame_RealtimeSignal)(nil),
		(*RelayFrame_ProtocolError)(nil),
	}
	file_relay_v2_relay_v2_proto_msgTypes[22].OneofWrappers = []any{
		(*RelayDataFrame_Connect)(nil),
		(*RelayDataFrame_Payload)(nil),
		(*RelayDataFrame_Ack)(nil),
		(*RelayDataFrame_Close)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relay_v2_relay_v2_proto_rawDesc), len(file_relay_v2_relay_v2_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_relay_v2_relay_v2_proto_goTypes,
		DependencyIndexes: file_relay_v2_relay_v2_proto_depIdxs,
		EnumInfos:         file_relay_v2_relay_v2_proto_enumTypes,
		MessageInfos:      file_relay_v2_relay_v2_proto_msgTypes,
	}.Build()
	File_relay_v2_relay_v2_proto = out.File
	file_relay_v2_relay_v2_proto_goTypes = nil
	file_relay_v2_relay_v2_proto_depIdxs = nil
}
